<?php

namespace Database\Seeders;

use App\Enums\UserRole;
use App\Models\AttendanceException;
use App\Models\AttendanceLog;
use App\Models\AttendanceScore;
use App\Models\AttendanceSummary;
use App\Models\BiometricData;
use App\Models\Tenant;
use App\Models\User;
use Carbon\Carbon;
use Carbon\CarbonPeriod;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;

class AccuracyTestSeeder extends Seeder
{
    public function run()
    {
        $this->command->info('Starting Accuracy Test Data Generation...');

        // 1. Wipe old data
        $this->command->info('Wiping old data...');
        DB::statement('TRUNCATE TABLE users CASCADE');
        DB::statement('TRUNCATE TABLE biometric_data CASCADE');
        DB::statement('TRUNCATE TABLE attendance_logs CASCADE');
        DB::statement('TRUNCATE TABLE attendance_scores CASCADE');
        DB::statement('TRUNCATE TABLE attendance_exceptions CASCADE');
        DB::statement('TRUNCATE TABLE attendance_summaries CASCADE');
        
        // 2. Generate Admin
        $this->command->info('Creating Admin User...');
        $admin = User::create([
            'name' => 'System Admin',
            'email' => 'admin@example.com',
            'employee_number' => 'ADMIN-001',
            'password' => Hash::make('password'),
            'role' => UserRole::ADMIN,
            'email_verified_at' => now(),
            'tenant_id' => 1
        ]);

        // 3. Generate 100 Employees
        $this->command->info('Creating 100 Employees...');
        $users = [];
        for ($i = 1; $i <= 100; $i++) {
            $user = User::create([
                'name' => "Employee $i",
                'email' => "employee$i@example.com",
                'employee_number' => "EMP-" . str_pad($i, 4, '0', STR_PAD_LEFT),
                'password' => Hash::make('password'),
                'role' => UserRole::GENERAL_USER,
                'email_verified_at' => now(),
                'tenant_id' => 1
            ]);
            $users[] = $user;

            // Generate Biometric Data
            BiometricData::create([
                'user_id' => $user->id,
                'user_name' => $user->name,
                'facial_encoding' => '[]', // Dummy
                'fingerprint_template' => '[]' // Dummy
            ]);
        }

        // 4. Generate 3 Months of Attendance Logs
        $this->command->info('Simulating 3 Months of Attendance Data for all employees...');
        
        $startDate = Carbon::now()->subMonths(3)->startOfMonth();
        $endDate = Carbon::now()->subDay();
        $period = CarbonPeriod::create($startDate, $endDate);

        $logsData = [];
        $scoresData = [];
        $exceptionsData = [];
        $summariesTracker = [];

        foreach ($period as $date) {
            if ($date->isWeekend()) {
                continue; // Skip weekends
            }

            $dateStr = $date->format('Y-m-d');

            foreach ($users as $user) {
                // Determine logic for this user on this day
                $chance = rand(1, 100);
                
                if ($chance <= 5) {
                    // 5% chance: Absent
                    $exceptionsData[] = [
                        'user_id' => $user->id,
                        'type' => 'other',
                        'note' => 'Absent - Generated by Accuracy Test',
                        'status' => 'approved',
                        'meta' => json_encode(['date' => $dateStr]),
                        'created_at' => $date,
                        'updated_at' => $date,
                        'tenant_id' => 1
                    ];
                    
                    // Track for summary
                    $this->updateSummary($summariesTracker, $user->id, $date, 'days_absent');
                    continue;
                }

                // Clock In (Usually between 07:45 and 08:15)
                $clockInTime = $date->copy()->setTime(7, 30)->addMinutes(rand(0, 90));
                
                $actionSource = (rand(1, 100) > 20) ? 'facial_recognition' : 'fingerprint_zkteco';

                $clockIn = [
                    'user_id' => $user->id,
                    'user_name' => $user->name,
                    'action' => 'clock_in',
                    'timestamp' => $clockInTime,
                    'network_info' => 'Accuracy Test Generator',
                    'source' => $actionSource,
                    'location_name' => 'HQ',
                    'created_at' => $clockInTime,
                    'updated_at' => $clockInTime,
                    'tenant_id' => 1
                ];

                // Clock Out (Usually between 17:00 and 18:00)
                // 2% chance they forgot to clock out
                if (rand(1, 100) > 2) {
                    $clockOutTime = $clockInTime->copy()->addHours(9)->addMinutes(rand(0, 120));
                    $clockOut = [
                        'user_id' => $user->id,
                        'user_name' => $user->name,
                        'action' => 'clock_out',
                        'timestamp' => $clockOutTime,
                        'network_info' => 'Accuracy Test Generator',
                        'source' => $actionSource,
                        'location_name' => 'HQ',
                        'created_at' => $clockOutTime,
                        'updated_at' => $clockOutTime,
                        'tenant_id' => 1
                    ];
                    
                    $logsData[] = $clockIn;
                    $logsData[] = $clockOut;
                    
                    // Calculate Score
                    $minutesLate = max(0, $clockInTime->diffInMinutes($date->copy()->setTime(8, 0), false) * -1);
                    $score = 100;
                    $status = 'on_time';
                    
                    if ($minutesLate > 0) {
                        $score = max(0, 100 - ($minutesLate)); // Deduct 1 point per minute late
                        if ($minutesLate <= 15) {
                            $status = 'grace';
                        } else {
                            $status = 'late';
                            $exceptionsData[] = [
                                'user_id' => $user->id,
                                'type' => 'incorrect_time',
                                'note' => "Late Arrival - $minutesLate minutes late",
                                'status' => 'pending',
                                'meta' => json_encode(['date' => $dateStr]),
                                'created_at' => $date,
                                'updated_at' => $date,
                                'tenant_id' => 1
                            ];
                        }
                    } elseif ($minutesLate < -15) {
                         $status = 'early';
                    }

                    $scoresData[] = [
                        'user_id' => $user->id,
                        'attendance_date' => $dateStr,
                        'total_points' => $score,
                        'clock_in_points' => $score,
                        'clock_out_points' => 0,
                        'clock_in_time' => $clockInTime->format('H:i:s'),
                        'clock_out_time' => $clockOutTime->format('H:i:s'),
                        'clock_in_status' => $status,
                        'clock_out_status' => 'normal',
                        'created_at' => $clockOutTime,
                        'updated_at' => $clockOutTime,
                        'tenant_id' => 1
                    ];

                    $this->updateSummary($summariesTracker, $user->id, $date, 'days_present', $score, 100, $status);
                } else {
                    // Missed clock out
                    $logsData[] = $clockIn;
                    $exceptionsData[] = [
                        'user_id' => $user->id,
                        'type' => 'missed_punch',
                        'note' => 'Missed Clock Out',
                        'status' => 'pending',
                        'meta' => json_encode(['date' => $dateStr]),
                        'created_at' => $date,
                        'updated_at' => $date,
                        'tenant_id' => 1
                    ];
                    
                    $scoresData[] = [
                        'user_id' => $user->id,
                        'attendance_date' => $dateStr,
                        'total_points' => 0,
                        'clock_in_points' => 0,
                        'clock_out_points' => 0,
                        'clock_in_time' => $clockInTime->format('H:i:s'),
                        'clock_out_time' => null,
                        'clock_in_status' => 'absent',
                        'clock_out_status' => 'absent',
                        'created_at' => $clockInTime,
                        'updated_at' => $clockInTime,
                        'tenant_id' => 1
                    ];
                    $this->updateSummary($summariesTracker, $user->id, $date, 'days_present', 0, 100, 'missed_out');
                }

                // Batch insert every 2000 records to save memory
                if (count($logsData) >= 2000) {
                    AttendanceLog::insert($logsData);
                    AttendanceScore::insert($scoresData);
                    AttendanceException::insert($exceptionsData);
                    $logsData = [];
                    $scoresData = [];
                    $exceptionsData = [];
                }
            }
        }

        // Insert remaining
        if (count($logsData) > 0) {
            AttendanceLog::insert($logsData);
            AttendanceScore::insert($scoresData);
            AttendanceException::insert($exceptionsData);
        }

        $this->command->info('Generating Summaries...');
        $finalSummaries = [];
        foreach ($summariesTracker as $userId => $months) {
            foreach ($months as $monthKey => $data) {
                [$year, $month] = explode('-', $monthKey);
                $periodStart = Carbon::create($year, $month, 1)->format('Y-m-d');
                $periodEnd = Carbon::create($year, $month, 1)->endOfMonth()->format('Y-m-d');
                
                $scorePercentage = $data['max_possible_score'] > 0 
                    ? ($data['total_score'] / $data['max_possible_score']) * 100 
                    : 0;

                $grade = 'F';
                if ($scorePercentage >= 90) $grade = 'A';
                elseif ($scorePercentage >= 80) $grade = 'B';
                elseif ($scorePercentage >= 70) $grade = 'C';
                elseif ($scorePercentage >= 60) $grade = 'D';

                $finalSummaries[] = [
                    'user_id' => $userId,
                    'period_type' => 'monthly',
                    'period_start' => $periodStart,
                    'period_end' => $periodEnd,
                    'total_score' => $data['total_score'],
                    'max_possible_score' => $data['max_possible_score'],
                    'score_percentage' => $scorePercentage,
                    'grade' => $grade,
                    'days_present' => $data['days_present'] ?? 0,
                    'days_absent' => $data['days_absent'] ?? 0,
                    'early_count' => $data['early_count'] ?? 0,
                    'on_time_count' => $data['on_time_count'] ?? 0,
                    'grace_count' => $data['grace_count'] ?? 0,
                    'late_count' => $data['late_count'] ?? 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                    'tenant_id' => 1
                ];
            }
        }
        
        foreach (array_chunk($finalSummaries, 500) as $chunk) {
            AttendanceSummary::insert($chunk);
        }

        $this->command->info('Accuracy Test Data Generation Complete!');
    }

    private function updateSummary(&$tracker, $userId, $date, $type, $score = 0, $maxScore = 0, $status = null)
    {
        $monthKey = $date->format('Y-m');
        if (!isset($tracker[$userId])) $tracker[$userId] = [];
        if (!isset($tracker[$userId][$monthKey])) {
            $tracker[$userId][$monthKey] = [
                'days_present' => 0, 'days_absent' => 0, 
                'total_score' => 0, 'max_possible_score' => 0,
                'early_count' => 0, 'on_time_count' => 0, 'grace_count' => 0, 'late_count' => 0
            ];
        }

        $tracker[$userId][$monthKey][$type]++;
        $tracker[$userId][$monthKey]['total_score'] += $score;
        $tracker[$userId][$monthKey]['max_possible_score'] += $maxScore;

        if ($status) {
            if ($status === 'early') $tracker[$userId][$monthKey]['early_count']++;
            if ($status === 'on_time') $tracker[$userId][$monthKey]['on_time_count']++;
            if ($status === 'grace') $tracker[$userId][$monthKey]['grace_count']++;
            if ($status === 'late') $tracker[$userId][$monthKey]['late_count']++;
        }
    }
}
